// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1DPWA.Data;

#nullable disable

namespace Parcial1DPWA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305014609_HacerEnvioIdOpcional")]
    partial class HacerEnvioIdOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial1DPWA.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Destinatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DepartamentoDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadosEnvioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaqueteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("EstadosEnvioId");

                    b.HasIndex("PaqueteId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.EstadosEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EstadosEnvioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EstadosEnvioId");

                    b.ToTable("EstadosEnvios");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EnvioId")
                        .HasColumnType("int");

                    b.Property<int?>("PaqueteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("PaqueteId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Cliente", b =>
                {
                    b.HasOne("Parcial1DPWA.Models.Cliente", null)
                        .WithMany("Clientes")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Destinatario", b =>
                {
                    b.HasOne("Parcial1DPWA.Models.Destinatario", null)
                        .WithMany("Destinatarios")
                        .HasForeignKey("DestinatarioId");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Envio", b =>
                {
                    b.HasOne("Parcial1DPWA.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcial1DPWA.Models.Destinatario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcial1DPWA.Models.EstadosEnvio", "EstadosEnvio")
                        .WithMany()
                        .HasForeignKey("EstadosEnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcial1DPWA.Models.Paquete", "Paquete")
                        .WithMany()
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Destinatario");

                    b.Navigation("EstadosEnvio");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.EstadosEnvio", b =>
                {
                    b.HasOne("Parcial1DPWA.Models.EstadosEnvio", null)
                        .WithMany("EstadosEnvios")
                        .HasForeignKey("EstadosEnvioId");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Paquete", b =>
                {
                    b.HasOne("Parcial1DPWA.Models.Envio", "Envio")
                        .WithMany()
                        .HasForeignKey("EnvioId");

                    b.HasOne("Parcial1DPWA.Models.Paquete", null)
                        .WithMany("Paquetes")
                        .HasForeignKey("PaqueteId");

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Cliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Destinatario", b =>
                {
                    b.Navigation("Destinatarios");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.EstadosEnvio", b =>
                {
                    b.Navigation("EstadosEnvios");
                });

            modelBuilder.Entity("Parcial1DPWA.Models.Paquete", b =>
                {
                    b.Navigation("Paquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
